### ISSUE TITLE
List of rides

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/liebeckm#1]
## Value Proposition

- As a user
- I want a list of rides
- in order to read them

## Description

- See Excalidraw Scribble

## Acceptance criteria

- [ ] Each ride on a different card
- [ ] Each card has
    - [ ] driver
    - [ ] rating
    - [ ] start and endpoint
    - [ ] time and date
    - [ ] free seats
    - [ ] price
    - [ ] a "auswählen"- button
- [ ] The list is scrollable
- [ ] The title "landwaerts" is displayed above the rides list

## Tasks

- [ ] Global Styles
- [ ] component/card
- [ ] write test
- [ ] Create db.js with rides
- [ ] Add to App

**Comment by LuYujin9** [comment]
The idea is very useful. There is only one small problem in description.  when so many informations are in one card, would it too small to read in smart phone ?

**Comment by liebeckm** [comment]
> The idea is very useful. There is only one small problem in description. when so many informations are in one card, would it too small to read in smart phone ?

Yeah, I have to think about how to arrange the information. On the right side is plenty of space left :)

**Comment by abieber1408** [comment]
Very Nice and a super idea.
Should it not be better so sort the cards by Place, "von" or "nach"?
It seems to be too much information for one user.

**Comment by liebeckm** [comment]
> Very Nice and a super idea. Should it not be better so sort the cards by Place, "von" or "nach"? It seems to be too much information for one user.

yes! This is a feature I will work on in another user story :)

**Comment by PReichetanz** [comment]
Nice rework, Melissa!

Just one thing: please remove the AC 'a "auswählen"- button', because you've already removed it from the scribble.
