### ISSUE TITLE
Detail page of ride

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/liebeckm#2]
## Value Proposition

- As a user
- I want to get detailed information for each ride
- in order to decide wether to book it or not

## Description

![Image](https://user-images.githubusercontent.com/123425806/227306802-5640545f-1da3-4abf-97cf-d714404c77c7.png)

## Acceptance criteria

- [ ] Driverpicture, -name, and -car are displayed on top
- [ ] Two cards:
-  [ ] The first card has overview of ride including
   -  [ ] driver
    - [ ] start and endpoint
    - [ ] time and date
    - [ ] free seats
    - [ ] price
- [ ] The second card has overview of ratings including
    - [ ] general rating on top
    - [ ] the two latest ratings including user name & picture
    - [ ] a "alle anzeigen"-button to show all ratings
- [ ] The Detailpage is scrollable
- [ ] The title "landwaerts" is displayed above the rides list
- [ ] There is a "jetzt buchen"- button
- [ ] There is a "zurück"-button

## Tasks

- [ ] Create feature branch
- [ ] update component/card
- [ ] update component/button
- [ ] add page pages/details
- [ ] write test
- [ ] Add to App

**Comment by alexWaligorski** [comment]
What a detailed story! Well done!!!!
Here some suggestions:
- remove the "jetzt buchen" button for now, as it will not be functional and the user story/product should not include any non functional items
- How does the screen look like, when no one has rated the driver yet? How do the star emojis look like in the header-part and will the "bewertungen" section diasappear or show a text saying "noch keine Bewertungen"
- Can you be more specific about the tests? What will be tested e.g. that a different text will be shown when there are no "Bewertungen"  
- Please indicate to where the "zurück" button will lead the user
- - Where is the "alle anzeigen" Button? Maybe exclude this functionality for now and write another story for the "ratings" component
-  Maybe make "ratings" a component on its own and nest it into your "card" component.

Hope, this helps!

**Comment by PReichetanz** [comment]
Hi Melissa,

nice work! Building on Alex' comment, just some thoughts of mine:
- You could simplify the story by removing the comments to a later story.
- Are the stars always 5 golden stars for now? Or is the rating already different? A rating component might be difficult, you could consider to display a `5/5` for now and replace it with stars in a later story.

**Comment by alexWaligorski** [comment]
Looks great! Simple and comprehensible.

**Comment by Kachev** [comment]
Hi Melissa, 

looks great!
