### ISSUE TITLE
"booking successful"-page

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/liebeckm#3]
## Value Proposition

- As a user
- I want to get a booking confirmation
- in order to know that my booking was successful

## Description

![Image](https://user-images.githubusercontent.com/123425806/227310657-6642f965-5520-4b47-8456-a4104827d7bd.png)

## Acceptance criteria
- [ ] The title "landwaerts" is displayed above
- [ ] below, there is a "Fahrt bei [NAME] gebucht!"-message
- [ ] One card with overview of ride including
   -  [ ] driver
    - [ ] start and endpoint
    - [ ] time and date
    - [ ] booked seats
    - [ ] contact data (phone)
    - [ ] price including note to pay with cash
    - [ ] automated email that sums up booking again

## Tasks

- [ ] Create feature branch
- [ ] update component/card
- [ ] add page pages/confirmation
- [ ] write test
- [ ] Add to App
